# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=resnet_optuna experiment=resnet50_rgb

defaults:
  - default

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  sweeper:
    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: 'sqlite:///data/db/resnet_optuna.db'
