# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
  save_dir: "${paths.output_dir}/tensorboard/"
  name: null
  log_graph: false
  default_hp_metric: false
  prefix: ""
  max_queue: 10
  flush_secs: 120
  # version: ""
